### ISSUE TITLE
Bug: uzbl seg-faults upon opening certain website(s)

### ISSUE THREAD

**Issue by GSI** [uzbl/uzbl#177]
Consistently, uzbl-browser crashes upon opening https://global.americanexpress.com/myca/intl/estatement/emea/statement.do?request_type=&Face=de_AT

Console output:

    # uzbl-browser                                                                                                          
    ** Message: PROP_TIMELINE_PROFILING_ENABLED has been deprecated
    
    [1]    30272 segmentation fault (core dumped)  uzbl-browser

**Comment by keis** [comment]
Hmm, looks like you would have to be logged in to see that page properly.

If you could get a gdb trace out of the core dump that would be great. `gdb <uzbl-binary> <core-file>` and the do `bt`

**Comment by GSI** [comment]
Have yet to figure out how to exactly use `gdb`;

Meanwhile I wanted to add **youtube.com** to the list of sites that crash uzbl.

**Comment by GSI** [comment]
Another one:

* Opens fine: https://www.google.com/maps
* Causes crash: https://www.google.com/maps?q
          
Note that all of these sites crash some seconds **after** they're 100 % loaded.

**Comment by keis** [comment]
Website crashes are typically an issue with webkit itself. Can you check if they work in epiphany (aka web)? also the output of `uzbl-browser -B` is useful if this happen to be down to specific library versions

**Comment by GSI** [comment]
All of the mentioned pages work in epiphany 3.18.2.

    # uzbl-browser -B
    Commit: 2012.05.14-1288-g5c24ea0
    GTK compile: 3.18.5
    GTK run: 3.18.6
    WebKit compile: 2.4.9
    WebKit run: 2.4.9
    WebKit2: 0
    libsoup compile: 2.52.2
    libsoup run: 2.52.2

... installed from the AUR (https://aur.archlinux.org/packages/uzbl-core-next-git)

**Comment by GSI** [comment]
I just updated to the latest git version (uzbl-core-next-git and uzbl-browser-next-git from Arch's AUR).

The sites mentioned no longer cause seg-faults.

**Comment by GSI** [comment]
For completeness sake:
I have not re-confirmed the issue just before the update.
It's resolution might have been caused by other parameters on my system.
