### ISSUE TITLE
Case-insensitive and smart case search

### ISSUE THREAD

**Issue by GSI** [uzbl/uzbl#180]
Searches are case-sensitive by default. I think we should set `search option case_insensitive` in **config** by default. PR welcome?

*Smart case* search would be even better, but according to the README, it seems that search is a Webkit feature, so I suppose we are restricted by what Webkit has to offer?

**Comment by keis** [comment]
sounds reasonable to me.

The search is indeed implemented by simply calling the webkit apis for search and there is some difference between wk1 and wk2 in this area I think

**Comment by mathstuf** [comment]
There are differences. WebKit2 has vastly improved performance since it doesn't have to search from scratch on the incremental search (for large pages using `search` directly is faster). But `case_insensitive` is a sensible option for the defaults.
