### ISSUE TITLE
Release 0.9

### ISSUE THREAD

**Issue by keis** [uzbl/uzbl#181]
0.9 is to be the release of the collected patches over the past years. It is only targeting webkit1 which is the only stable webkit target for now. uzbl-next will drop webkit1 support and focus on getting all features working in webkit2

Please help test the master branch and report any major issues. If you have tested it and it works fine please drop a comment below to that effect.

ping @sandio @GSI @ballsystemlord @rumpelsepp

**Comment by GSI** [comment]
I am trying to make an Arch package of **master** for easy switching between the two versions, but even though I updated `PKGBUILD` and `.SRCINFO`, it always ends up using **next**.

In case we have anybody familiar with Arch packaging, I'd appreciate help with this.

(Might also check with the current maintainer of the AUR package.)

**Comment by mathstuf** [comment]
`next` is the default branch when cloning. Explicitly mention the `master` branch where needed.

**Comment by nocylah** [comment]
Hi, I'm the AUR package maintainer. A quick search-and-replace of 'next' to 'master' does it - here's a [diff](https://gist.github.com/nocylah/7d8add8dae1bc92d1317) you can apply to the package repo.

**Comment by GSI** [comment]
Thanks @nocylah, that was what I did, but I was confused when `makepkg` reset the **pkgver** *2012.05.14.1301.gae4181e*.

However, now I verified that **ae4181** is actually the most recent commit in **master**.

What had actually caused trouble upon install was the `arch=(any)` declaration in the **uzbl-browser** and **uzbl-tabbed** sections, which caused the resulting file names not to be found by `makepkg -si`.

**Comment by nocylah** [comment]
@GSI Ah, I see what you mean. Thanks for pointing out the `arch=` inconsistency, didn't know that was causing problems.

**Comment by ballsystemlord** [comment]
I noticed that there is not release a release nor an announcement on uzbl.org are we in a prerelease state or was that over looked?

**Comment by keis** [comment]
No. we've not cut a release yet. If you're looking for a rc take a look at the master branch

**Comment by keis** [comment]
But I guess we should be kinda close.

@mathstuf do you know what's needed to update the website? I assume https://github.com/uzbl/uzbl-website should be updated first but is there some manual step after that?

**Comment by mathstuf** [comment]
@barrucadu runs the website; I have no access to actually update it. He has been responsive in the past.

**Comment by barrucadu** [comment]
I've just set up a cronjob to pull changes to the website frequently, so now updating uzbl/uzbl-website and waiting a bit is the only step.

**Comment by keis** [comment]
great stuff @barrucadu

**Comment by Dieterbe** [comment]
It's aliiiiive !

**Comment by keis** [comment]
I see no major issues, that I can reproduce, that should be stopping 0.9 so I'll cut that release this weekend. Hopefully getting more eyes on it will help track down the more obscure crashes and the like. And there's always 0.9.1 to look forward to

**Comment by keis** [comment]
The release is tagged :dancers: 

I also updated the default branch to 'master' as this will moving forward next could be a bit crazy.
