### ISSUE TITLE
Duplicated REQ_NEW_WINDOW from link

### ISSUE THREAD

**Issue by keis** [uzbl/uzbl#185]
With a simple test page like
```
 <a href="http://google.com" target="_blank">test</a>
```

each time you click the link uzbl will send more and more REQ_NEW_WINDOW events. Starting from 1 and increasing by 1 each time so the 5th time you click the link 5 new windows are requested.

**Comment by GSI** [comment]
Is this related (?):

Some of the windows opened this way, seem to be unable to connect to uzbl-event-manager - at least there's just "[]" in the status bar where there should be "[Cmd]" instead.

**Comment by keis** [comment]
I don't think so. I have not seen that for a while. There is still a race condition (I think) when starting uzbl the first time when there is no event manager running

**Comment by GSI** [comment]
I see both quite regularly:

1. When I restart my system after a crash, uzbl instances start with "[]". I then have to run the command "uzbl-event-manager" once which then allows uzbl to start correctly.

2. Sometimes when I open a link in a new window, nothing pops up unless I click again - but upon clicking again, both (or more) windows open. Just that some of them open with [] while some open with [Cmd].

**Comment by keis** [comment]
I'm not really sure how to fix 1. I don't think there is a good way to check if we can actually connect to the socket without depending on something like socat for uzbl-browser

I think the duplicate windows should be fixed by #186 if you have some small html snippet that demonstrate the other issues that would be great

**Comment by javigazi** [comment]
```
** (uzbl-core:27114): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Commit: e297545
GTK compile: 3.18.9
GTK run: 3.18.9
WebKit compile: 2.14.5
WebKit run: 2.14.5
WebKit2: 1
libsoup compile: 2.52.2
libsoup run: 2.52.2
```
hello, the problem is relevant, when I open the link from the example, then a duplicate window opens. 

EVENT [1544] REQ_NEW_WINDOW 'http://google.com/'
EVENT [1544] REQ_NEW_WINDOW ''

p.s. sorry, for my english

**Comment by keis** [comment]
the second event looks really odd. is it opening an empty window? if so this might be a new issue

**Comment by javigazi** [comment]
create #369
