### ISSUE TITLE
Allow opening URLs without explicit command line switch

### ISSUE THREAD

**Issue by GSI** [uzbl/uzbl#187]
The issue:

    BROWSER='uzbl-browser -u'
    $BROWSER http://uzbl.org
    # => zsh: command not found: uzbl-browser -u

To avoid this, simply running `uzbl-browser http://uzbl.org` (without `-u/--uri`) should be possible.

**Comment by keis** [comment]
Looks like this was intentionally removed by 520fbf and upgrading.md tells the same story.

```
For `uzbl-core`, a URI must now use the `--uri` flag; the first non-flag
argument is no longer interpreted as a URI (this is to avoid confusion of what
should be loaded with `uzbl-core --uri page1 page2`).
```

So I'm a bit hesitant to simply restore this. But maybe removing -u is a better option. WDYT @mathstuf ?

**Comment by mathstuf** [comment]
Without specifying what should happen with `uzbl-core page1 page2`, I'd rather keep it under `-u`.

**Comment by GSI** [comment]
Maybe generall accept one and only one URI?

`uzbl-core page1 page2` would open just page1 and generate a warning regarding the rest.

**Comment by keis** [comment]
I guess we could recommmend people to configure BROWSER to xdg-open and then set uzbl as the default browser.

Also just discovered with need some extra bits for the desktop file for that to work

**Comment by GSI** [comment]
I don't quite get the issue with just ditching -u / --uri altogether (?)

The expected behaviour of `$BROWSER $uri` is to open the given URI.
(Of the ones I tested, uzbl is the only one not doing so.)

Requiring an additional flag causes known and future issues.

@keis wrote:
> I guess we could recommmend people to configure BROWSER to xdg-open and then set uzbl as the default browser.

Bad idea :) (xdg-open is not a BROWSER)

My xdg-open replacement, for example, executes `$BROWSER` for any URL provided. So that would create a loop unless I (and every other linopen-user) "cripples" their config by explicitly naming `$their_currently_preferred_browser`.

**Comment by mathstuf** [comment]
So it seems other browsers open all URLs given on the command line. `uzbl-core` only supports one. `uzbl-tabbed` and `uzbl-browser` could take multiples on the command line, but I don't think `uzbl-core` itself should.

**Comment by keis** [comment]
@GSI ok, fair point

I wouldn't worry too much about multiple uris as uzbl is still specifically a single page browser. Exiting with non-zero when we get more should be a reasonable option for core. And I would suggest `uzbl-browser` should do the same to keep things simple for now and not have to grok the arguments for uzbl-core.

**Comment by keis** [comment]
Checked just now and `uzbl-tabbed` already works this way

**Comment by keis** [comment]
So does droppign -u and going with only the first argument as url and error if there is more sound like a good aproach for core?

**Comment by mathstuf** [comment]
I still think `uzbl-core` should have a flag and `uzbl-browser` act more like a browser there.

Keep `-u` and, if it isn't given, use the first argument and warn if adding argument parsing to `uzbl-browser` is onerous?

**Comment by keis** [comment]
Is there really any benefit to -u over a positional argument in core?

It's not very complex to add some getopt magic to uzbl-browser as it would not have to know about any specifics of the arguments except -u. But there still code in two placing fiddling with the opts which I think we should avoid if possible

**Comment by mathstuf** [comment]
I guess not. We should output that we're ignoring arguments to `stderr` though.
