### ISSUE TITLE
[0.9] SSL CA bundle not found (Arch Linux)

### ISSUE THREAD

**Issue by GSI** [uzbl/uzbl#189]
With the default config on Arch Linux:

    # uzbl-browser
    (uzbl-core:1192): libsoup-WARNING **: Could not set SSL credentials from '/etc/ssl/certs/ca-bundle.crt': Failed to open file '/etc/ssl/certs/ca-bundle.crt': No such file or directory

Setting it to the actual path resolves the issue:

`set ssl_ca_file = /etc/ssl/certs/ca-certificates.crt`

... but would there be any way of referencing the bundle "cross-distribution" safely?

**Comment by keis** [comment]
I don't know of any standard way of getting the path of the bundle. And there is more candidates than you can shake a stick at

https://www.happyassassin.net/2015/01/12/a-note-about-ssltls-trusted-certificate-stores-and-platforms/

**Comment by mathstuf** [comment]
Yeah, this is a patch that Arch should carry. I think the `p11-kit` toolset uses the path that's in the configuration.

**Comment by keis** [comment]
Sure. Having a patch for the default config should not be a big deal.
