### ISSUE TITLE
[0.9] Floating point formatting problems

### ISSUE THREAD

**Issue by GSI** [uzbl/uzbl#190]
`set zoom_level 2.0` works, but being more precise (eg `set zoom_level 2.2`) seems to have no effect.

Thus I (have to) use the following workaround in order to set a zoom_level of 1.3:

`@cbind  0   = chain 'set zoom_level 1.0' 'zoom_in' 'zoom_in' 'zoom_in'`

_(Maybe this issue is of minor relevance for the 0.9 release, but as it also exists in **next** ...)_

**Comment by keis** [comment]
I can't reproduce this.

Is it no effect at all from "2.2" or just the same as "2.0"? I'm guessing it could have to do with how we parse numbers because I can put weird stuff like "3foo" and it's treated as a plain 3

**Comment by GSI** [comment]
Seems you're right. "2.2" sets it to "2.0". "1.9" sets it to "1.0".

Confirming "3foo" behaviour;

**Comment by keis** [comment]
You don't happen to be using a locale that expects floating point to be written "2,2"?

**Comment by GSI** [comment]
I happen to :)

... and using `set zoom_level 1,3` does what I'd expect from "1.3".

**Comment by keis** [comment]
Sounds like we should force "standard" number formats because you don't really want locale specific config files

**Comment by keis** [comment]
A related issue reported on IRC. When dumping variables after connecting to a event-manager  `zoom_step` is written as "0,1" which makes python throw an error when trying to parse it

**Comment by f8l** [comment]
I want to add that this happens because of a locale in which the decimal separator is not a dot (‘pl_PL.UTF-8’ in my case).

**Comment by mathstuf** [comment]
It's a pity Unix screwed up and locale is a process-wide thing. Setting the locale to "C" would be best for the I/O and uzbl threads (but the GUI can still be in whatever locale the user wants).

**Comment by keis** [comment]
There is stuff like g_ascii_formatd that we should be able to use

http://www.freedesktop.org/software/gstreamer-sdk/data/docs/latest/glib/glib-String-Utility-Functions.html#g-ascii-formatd
