### ISSUE TITLE
Contents in "developer" windows are terribly tiny

### ISSUE THREAD

**Issue by GSI** [uzbl/uzbl#198]
... I mean the one that's opened upon _RMB > Inspect element_

I suppose that's provided that way by Webkit.

Is there still a way to increase it's font sizes?

**Comment by mathstuf** [comment]
Webkit1 is not really high-dpi aware. Probably fixed by webkit2.

**Comment by mathstuf** [comment]
But no, I don't think there's a way to fix this without access to the widgets in the inspector window (which might be possible with the GTK inspector thing).

**Comment by keis** [comment]
Not much we can do about this as it's all webkit and as wk1 is not likely to get this fixed ever

**Comment by GSI** [comment]
Let's see how WK2 goes about this.
