### ISSUE TITLE
<Space> binding no longer works

### ISSUE THREAD

**Issue by mathstuf** [uzbl/uzbl#209]
Something broke the `<Space>` binding.

Other fun things happened in the meantime of me trying simple fixes. This crashes the event manager:

```uzbl
@cbind  \              = scroll vertical 50%
```

```
Feb 04 14:42:19 megas uzbl-event-manager[22073]: uzbl-instance[22793]: ERROR: error in handler for 'MODE_BIND'
Feb 04 14:42:19 megas uzbl-event-manager[22073]: Traceback (most recent call last):
Feb 04 14:42:19 megas uzbl-event-manager[22073]: File "/home/boeckb/.local/share/uzbl/python/uzbl/core.py", line 173, in event
Feb 04 14:42:19 megas uzbl-event-manager[22073]: handler(*args, **kargs)
Feb 04 14:42:19 megas uzbl-event-manager[22073]: File "/home/boeckb/.local/share/uzbl/python/uzbl/plugins/bind.py", line 384, in parse_mode_bind
Feb 04 14:42:19 megas uzbl-event-manager[22073]: self.mode_bind(modes, glob, command)
Feb 04 14:42:19 megas uzbl-event-manager[22073]: File "/home/boeckb/.local/share/uzbl/python/uzbl/plugins/bind.py", line 338, in mode_bind
Feb 04 14:42:19 megas uzbl-event-manager[22073]: bind = Bind(glob, handler, *args, **kargs)
Feb 04 14:42:19 megas uzbl-event-manager[22073]: File "/home/boeckb/.local/share/uzbl/python/uzbl/plugins/bind.py", line 188, in __init__
Feb 04 14:42:19 megas uzbl-event-manager[22073]: raise ArgumentError('glob cannot be blank')
Feb 04 14:42:19 megas uzbl-event-manager[22073]: uzbl.plugins.bind.ArgumentError: glob cannot be blank
Feb 04 14:42:19 megas uzbl-event-manager[22073]: Traceback (most recent call last):
Feb 04 14:42:19 megas uzbl-event-manager[22073]: File "/home/boeckb/.local/share/uzbl/python/uzbl/core.py", line 173, in event
Feb 04 14:42:19 megas uzbl-event-manager[22073]: handler(*args, **kargs)
Feb 04 14:42:19 megas uzbl-event-manager[22073]: File "/home/boeckb/.local/share/uzbl/python/uzbl/plugins/bind.py", line 384, in parse_mode_bind
Feb 04 14:42:19 megas uzbl-event-manager[22073]: self.mode_bind(modes, glob, command)
Feb 04 14:42:19 megas uzbl-event-manager[22073]: File "/home/boeckb/.local/share/uzbl/python/uzbl/plugins/bind.py", line 338, in mode_bind
Feb 04 14:42:19 megas uzbl-event-manager[22073]: bind = Bind(glob, handler, *args, **kargs)
Feb 04 14:42:19 megas uzbl-event-manager[22073]: File "/home/boeckb/.local/share/uzbl/python/uzbl/plugins/bind.py", line 188, in __init__
Feb 04 14:42:19 megas uzbl-event-manager[22073]: raise ArgumentError('glob cannot be blank')
Feb 04 14:42:19 megas uzbl-event-manager[22073]: uzbl.plugins.bind.ArgumentError: glob cannot be blank
```

**Comment by keis** [comment]
With #210 that I just opened to get 'p to work again binding space would be written as

```
@cbind " " = scroll vertical 50%
```

**Comment by mathstuf** [comment]
Well, it used to be one of those special things: `<Space>`, so something is up. GTK being weird underneath?

**Comment by mathstuf** [comment]
Also, was wondering how something which appeared to fix my problem was a lower number than my issue. Had to look over my shoulder to see if you were there :P .

**Comment by keis** [comment]
haha, yeah. weird coincidence but used the wrong target branch :(

the events for pressing space is a bit odd from core, so I think you might be right blaming in on the GTK 
```
EVENT [23916] KEY_PRESS '' ' '
EVENT [23916] KEY_RELEASE '' space
```

**Comment by GSI** [comment]
> @cbind " " = scroll vertical 50%

Think that should be a default binding, given it's very common in other browsers;

Is this now the correct way to declare it?

**Comment by mathstuf** [comment]
Well, it depends on your GTK version apparently :/ . But it is default. Most other browsers do a full page scroll though.

**Comment by keis** [comment]
I did dig into this a bit and I think it's related to using the IM commit callback. because space gets translated and "commited" into a " " and the plain key press is the ignored.

If we can get away with changing the default binding I would suggest we go with that because keyboard input is bound to be weird considering dead keys all that madness anyway and that we avoid complicating core much more.

**Comment by mathstuf** [comment]
Hmm, fair enough. This should be added to `UPGRADING.md` and the default configuration updated.

**Comment by keis** [comment]
Should be fixed in master now

**Comment by mathstuf** [comment]
Sigh. GTK *shakes fist*

```
EVENT [13910] KEY_PRESS '' ' '
EVENT [13910] VARIABLE_SET keycmd str '<span underline="single"> </span>'
EVENT [13910] KEY_RELEASE '' space
EVENT [13910] VARIABLE_SET modcmd str ''
```

**Comment by keis** [comment]
Still not working or just venting about gtk? :stuck_out_tongue_closed_eyes:

**Comment by mathstuf** [comment]
Yes :) .

**Comment by mathstuf** [comment]
Event manager logs:

```
Feb 10 17:42:05 megas uzbl-event-manager[967]: uzbl-instance[1249]: DEBUG: --> MODE_BIND ("command  ' '            = scroll vertical 50%",)
Feb 10 17:42:05 megas uzbl-event-manager[967]: uzbl-instance[1249]: DEBUG:   --> ADDED_MODE_BIND ('command', "' '", <Bind(glob="' '", bid=42, command='scroll vertical 50%')>)
Feb 10 17:42:05 megas uzbl-event-manager[967]: uzbl-instance[1249]: INFO: added bind command ' ' <Bind(glob="' '", bid=42, command='scroll vertical 50%')>
Feb 10 17:42:05 megas uzbl-event-manager[967]: uzbl-instance[1249]: DEBUG: --> MODE_BIND ("command  '<Shift> '     = scroll vertical -50%",)
Feb 10 17:42:05 megas uzbl-event-manager[967]: uzbl-instance[1249]: DEBUG:   --> ADDED_MODE_BIND ('command', "'<Shift> '", <Bind(glob="'<Shift> '", bid=43, command='scroll vertical -50%')>)
```

Quoting is weird.

**Comment by keis** [comment]
What it looks like for me
```
[1455176830.971437] uzbl-instance[19213]: DEBUG: --> MODE_BIND ('command  " "          = scroll vertical 100%',)
[1455176830.971638] uzbl-instance[19213]: DEBUG:   --> ADDED_MODE_BIND ('command', ' ', <Bind(glob=' ', bid=34, command='scroll vertical 100%')>)
```

I wonder if the change to setuptools for installing messed something up and it's not overwriting the old code properly

**Comment by keis** [comment]
Oh, or maybe this was on `next`. looks like I forgot to merge with master :sweat:

**Comment by keis** [comment]
Did you get a chance to test this again @mathstuf. It all works here.

**Comment by mathstuf** [comment]
Not yet. Didn't $DAYJOB today and no Internet for the home box until I figure out wireless issues.

**Comment by keis** [comment]
Ok. no worries. This could be a big deal if it's still not working so really want to make sure it's fixed. But then I think I'm calling 0.9. Sounds good?

**Comment by keis** [comment]
Bump :cat:

**Comment by mathstuf** [comment]
OK, things work for `" "`, but `"<Shift> "` isn't working. Seems that we lost the ability to modify space when it became a character versus a `<Key>`.

**Comment by mathstuf** [comment]
Using:

```uzbl
@modmap " "             <Space>
```

seems to be a compatible compromise.

**Comment by GSI** [comment]
Any reason not to include this in the default config?

`@cbind  <Shift><Space>      = scroll vertical -100%`

**Comment by mathstuf** [comment]
I have that in mine (though with 50%). A PR would work :) .
