### ISSUE TITLE
Critical Error on Console

### ISSUE THREAD

**Issue by jameskirsop** [uzbl/uzbl#211]
When trying to run uzbl-browser from the command line, I get the following twice on the console:

`(uzbl-core:1704): GLib-GObject-CRITICAL **: g_closure_unref: assertion 'closure->ref_count > 0' failed`

This is on the latest build of uzbl-next, backed on to the latest libwebkitgtk-3.0 available in official raspbian repositories (2.4.1-1rpi53rpi1g on the RaspberryPi's I'm running this on).

**Comment by keis** [comment]
That specific call is originating from within webkit or some other library. If you could get a backtrace that could help narrow the issue down. Make sure you have debug packages installed if those are separate from the core libraries.

run uzbl in gdb and break on warnings
```
G_DEBUG=fatal_warnings gdb uzbl-core
```

type `r` to start and after you get back to the prompt when it crashes do `bt`

**Comment by mathstuf** [comment]
Maybe we should ship my `uzbl-gdb` and `uzbl-valgrind` scripts which are `uzbl-browser`, but run underneath gdb and valgrind for testing since it does some important stuff (setting up the EM).

**Comment by keis** [comment]
Sounds like good scripts to have around. It would be bad to clutter the path though (ok, I'm a <tab> addict) but maybe putting those in the examples somewhere would be good.

**Comment by jameskirsop** [comment]
I think we can close this one off - I've compiled next against webkit2gtk from the latest packages for stretch with no such issues.
