### ISSUE TITLE
Do we use this tracker or the uzbl (FlySpray) one? I'm confused.

### ISSUE THREAD

**Issue by timofonic** [uzbl/uzbl#216]
Hello.

Do we use this tracker or the uzbl (FlySpray) one? I'm confused.

See the question on uzbl.org issue tracker. Sorry for the recursivity, I intended to give the most visibility to this:
http://www.uzbl.org/bugs/index.php?do=details&task_id=384
Kind regards.

**Comment by keis** [comment]
github issues is more convenient to work with so we enabled that. To ffollow through and disable flyspray would be a natural step

**Comment by mathstuf** [comment]
Migrating issues from Flyspray would be a first step. There are some things there (mainly feature requests) which should be tracked here.

**Comment by keis** [comment]
Yes. Agreed. Lets not drop it cold. But I'll change the readme etc to point to github.
