### ISSUE TITLE
Outdated website

### ISSUE THREAD

**Issue by timofonic** [uzbl/uzbl#217]
Hello.

I see the website is terribly outdated, but the GitHub repository keeps active.

Why?

I posted this issue in uzbl.org issue tracker for better visibility (not sure where to ask, confusing redundancy): http://www.uzbl.org/bugs/index.php?do=details&task_id=385

Kind regards.

**Comment by keis** [comment]
The website reflects the latest release which is also very outdated. See #181 to follow the plans for creating a new release

**Comment by keis** [comment]
Source repo of website is updated and actual website should follow soon
