### ISSUE TITLE
How WebKit2 limitations have been surpassed? What about considering other web engines?

### ISSUE THREAD

**Issue by timofonic** [uzbl/uzbl#218]
Hello.

What about the limitations of WebKit2? How have they been surpassed?

Is WebKit2 the best choice now Google forked it to Blink? 

I tried to look about the current status of web engines, it seems chaos (forking) won order (mergin):
- WebKit
* Blink
* ?
- Gecko
* Goanna (Pale Moon).

Would somebody be nice to explain me about the current status of the Open Source web engines ecosystem? Features, number of developers and development activity, supported platforms, efficiency.

Kind regards.

**Comment by keis** [comment]
webkit is healthy as far as I can tell and actively supported by the gnome guys. However uzbl is currently stuck on wk1. It is going to be a lot of working making everything work in wk2 but not impossible.

I can't really tell you much about blink or gecko

**Comment by mathstuf** [comment]
Blink is not a standalone library, so that is just never going to work unless Google starts being…not Google. Gecko is also on its way out. Never heard of Goanna. Servo would be interesting.

**Comment by keis** [comment]
Without some specific suggestions I don't think this issue is going very far so I'm closing it

**Comment by mathstuf** [comment]
http://chrislord.net/index.php/2016/02/24/the-case-for-an-embeddable-gecko/

**Comment by timofonic** [comment]
@mathstuf 

Interesting...
What about Goanna too?

**Comment by mathstuf** [comment]
Same problem as Blink. From their website: "Goanna does not have a stand-alone source, since it can't be used as a stand-alone library".
