### ISSUE TITLE
Downloads work, but progress stays at 0%

### ISSUE THREAD

**Issue by GSI** [uzbl/uzbl#222]
Please paste the output of `uzbl-core --bug-info` here:

```
Commit: 2012.05.14-1337-g2bdfdf7
GTK compile: 3.18.7
GTK run: 3.18.8
WebKit compile: 2.4.9
WebKit run: 2.4.9
WebKit2: 0
libsoup compile: 2.52.2
libsoup run: 2.52.2
```

Heading says it all.

**Comment by keis** [comment]
current-size signal is no longer triggering from webkit so no progress is reported by core. It's not working on next with wk2 either. Will have to dig into this a bit deeper at some point.

**Comment by GSI** [comment]
Apparently this was resolved by your fixes. Thanks!

Feel free to reopen if there's still something left.

**Comment by keis** [comment]
huh, wtf. suddenly everything works over here as well. My fix was only to remove after it was finished so I have to assume something was fixed in webkit too. odd.
