### ISSUE TITLE
[0.9] HTTP auth handler is broken

### ISSUE THREAD

**Issue by moorchegue** [uzbl/uzbl#239]
So, first of all auth handler was dying on:

```
Traceback (most recent call last):
  File "/usr/share/uzbl/examples/data/scripts/auth.py", line 55, in <module>
    me, info, host, realm = sys.argv
ValueError: too many values to unpack
```

I printed out sys.argv, it looked like this:
```
['/usr/share/uzbl/examples/data/scripts/auth.py', 'tulup.ru', 'tulup.ru', 'initial', 'http_basic', 'origin', '443', 'cant_save']
```

So first four values are still what we need, and the rest we don't, I guess.

So script stopped failing after I fixed that, but auth still didn't work. So I set enable_builtin_auth to 1 and commented out all auth handlers and that worked. A bit weird, though: it doesn't wait till I enter credentials and page in the background shows auth error, so I have to refresh the page after I enter username/password and then it works.

Is there a right approach to this?

Also just a reminder of an old problem: would it be possible to share HTTP auth between different tabs in uzbl-tabbed? Right now you have to authorize in every single tab you open with the same URL.

Please paste the output of `uzbl-core --bug-info` here:

```
Commit: v0.9.0
GTK compile: 3.18.9
GTK run: 3.18.9
WebKit compile: 2.4.9
WebKit run: 2.4.9
WebKit2: 0
libsoup compile: 2.52.2
libsoup run: 2.52.2
```

**Comment by keis** [comment]
hmm. looks like this script was never updated after the `AUTHENTICATE` event was dropped. I'm not entirely sure how this is supposed to work now. @mathstuf any ideas?

**Comment by keis** [comment]
The way to share auth between instances would be to have the auth script maintain a inventory (possibly just a plain text file of host:user:pass) and provide those when needed.

**Comment by moorchegue** [comment]
Makes sense.

Here's another thing. Builtin auth seems to work fine with Nginx, but fails to work with Apache. At least that's the major difference I can see between two servers I've authed so far. Here's what it gives me:

```
Unauthorized

This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.
```

I'm going to Wireshark it to figure out what exactly is going on. BTW, is there a way to see HTTP headers using Inspector the way it's done in Chrome?

**Comment by keis** [comment]
the inspector is not at all modifed by uzbl however the version in webkit1 is very old so it's possible that feature is just not there.

**Comment by mathstuf** [comment]
There are probably more arguments than expected to the authentication_handler than the script is expecting now since uzbl now exposes more info. Using `[:4]` should help. As for sharing between tabs, the script could do some timeout for with memory. Or consult a database (libsecret? pass?) for stored credentials.

**Comment by moorchegue** [comment]
More details on builtin auth. So I missed nother major difference between servers: the one that works fine uses HTTPS, and the one that doesn't — HTTP. So obviously I couldn't sniff HTTPS headers, but I did it with HTTP server (the problematic one), here's how it looks:

```
    GET / HTTP/1.1\r\n
        [Expert Info (Chat/Sequence): GET / HTTP/1.1\r\n]
            [GET / HTTP/1.1\r\n]
            [Severity level: Chat]
            [Group: Sequence]
        Request Method: GET
        Request URI: /
        Request Version: HTTP/1.1
    Host: docs.***.co\r\n
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\n
    Accept-Encoding: gzip, deflate\r\n
    User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML; like Gecko) Uzbl/v0.9.0\r\n
    Connection: Keep-Alive\r\n
    \r\n
    [Full request URI: http://docs.****.co/]
    [HTTP request 1/1]

    HTTP/1.1 401 Unauthorized\r\n
        [Expert Info (Chat/Sequence): HTTP/1.1 401 Unauthorized\r\n]
            [HTTP/1.1 401 Unauthorized\r\n]
            [Severity level: Chat]
            [Group: Sequence]
        Request Version: HTTP/1.1
        Status Code: 401
        Response Phrase: Unauthorized
    Date: Sat, 19 Mar 2016 06:57:02 GMT\r\n
    Server: Apache/2.4.7 (Ubuntu)\r\n
    WWW-Authenticate: Digest realm="******", nonce="********", algorithm=MD5, domain="/*****", qop="auth"\r\n
    Content-Length: 458\r\n
        [Content length: 458]
    Keep-Alive: timeout=5, max=100\r\n
    Connection: Keep-Alive\r\n
    Content-Type: text/html; charset=iso-8859-1\r\n
    \r\n
    [HTTP response 1/1]
    [Time since request: 0.182486378 seconds]
    [Request in frame: 77]

    HTTP/1.1 401 Unauthorized\r\n
        [Expert Info (Chat/Sequence): HTTP/1.1 401 Unauthorized\r\n]
            [HTTP/1.1 401 Unauthorized\r\n]
            [Severity level: Chat]
            [Group: Sequence]
        Request Version: HTTP/1.1
        Status Code: 401
        Response Phrase: Unauthorized
    Date: Sat, 19 Mar 2016 06:57:03 GMT\r\n
    Server: Apache/2.4.7 (Ubuntu)\r\n
    WWW-Authenticate: Digest realm="*****", nonce="******", algorithm=MD5, domain="/*****", qop="auth"\r\n
    Content-Length: 458\r\n
        [Content length: 458]
    Keep-Alive: timeout=5, max=99\r\n
    Connection: Keep-Alive\r\n
    Content-Type: text/html; charset=iso-8859-1\r\n
    \r\n
    [HTTP response 2/2]
    [Time since request: 0.186718490 seconds]
    [Prev request in frame: 77]
    [Prev response in frame: 79]
    [Request in frame: 81]
```

So request doesn't contain any auth data. Could it be intentional security restriction — not to send http auth data using unsecure protocol? And if so, maybe it's configurable?

**Comment by keis** [comment]
looks like it's also trying to use the `auth` command that was removed :sweat:

**Comment by moorchegue** [comment]
More on built in auth issue. It seems that it doesn't work/support Apache Digest auth. HTTP/HTTPS doesn't matter, Apache/Nginx obviously also doesn't make any difference, the only difference I found is that the Basic Auth works, and Digest one doesn't.

I'm not sure if that's an issue or not. I think once Uzbl auth handler is fixed it wouldn't matter. Although it's always good to have a alternative/fallback solution.

**Comment by keis** [comment]
aha. that's interesting. Thanks for digging into that @moorchegue

**Comment by keis** [comment]
Fixed the auth script but found out there is a third (also bulit in) auth system that is causing trouble. Running without an auth handler and with `enable_builtin_auth 0` it will be visible and work properly.

**Comment by keis** [comment]
Relevant code in webkit https://github.com/WebKit/webkit/blob/master/Source/WebCore/platform/network/soup/SoupNetworkSession.cpp#L123 

I'm going to try to rewrite enable_builtin_auth to use g_signal_handler_block/g_signal_handler_unblock

**Comment by moorchegue** [comment]
> Running without an auth handler and with enable_builtin_auth 0 it will be visible and work properly.

Ha, nice find! So far it works best (unlike `enable_builtin_auth 1` this doesn't load a page before credentials are submitted). However it doesn't work with Digest auth as well.
