### ISSUE TITLE
uzbl crashes when zooming to big levels

### ISSUE THREAD

**Issue by GSI** [uzbl/uzbl#242]
Please paste the output of `uzbl-core --bug-info` here:

```
Commit: v0.9.0-1-gca4a63a
GTK compile: 3.18.8
GTK run: 3.18.9
WebKit compile: 2.4.9
WebKit run: 2.4.10
WebKit2: 0
libsoup compile: 2.52.2
libsoup run: 2.52.2
```

From `dmesg`:

`[14927.492699] uzbl-core[2326]: segfault at 7f3f5f54b000 ip 00007f3fe892947c sp 00007ffdb5964b08 error 4 in libpixman-1.so.0.34.0[7f3fe889b000+9f000]`

_(Text-only zoom appears to be unaffected. I suppose it doesn't use libpixman as no images are being zoomed.)_

**Comment by mathstuf** [comment]
What is `zoom_level` just before it crashes?

Try:

```uzbl
@on_set zoom_level print \@zoom_level
```

and watch the event logs (the `-p` flag).

**Comment by GSI** [comment]
Closing, as I am unable to reproduce the issue since switching to **nouveau** (#221).
Will reopen if necessary;
