### ISSUE TITLE
Adding multiple custom CSS files fails

### ISSUE THREAD

**Issue by GSI** [uzbl/uzbl#256]
Please paste the output of `uzbl-core --bug-info` here:

```
Commit: v0.9.0-21-g4851bae
GTK compile: 3.20.2
GTK run: 3.20.2
WebKit compile: 2.4.10
WebKit run: 2.4.10
WebKit2: 0
libsoup compile: 2.54.0
libsoup run: 2.54.0
```

Given it's name is `add`, I'd expect this to work
```
css add file://@config_home/style.css
css add file://@config_home/per-site-styles.css
```

However, the second one is ignored.

Also tried this:
```
css add file://@config_home/style.css file://@config_home/per-site-styles.css                                                                              
```

Also tried using `@import 'per-site-styles.css';` from within **style.css**.

Any other way to achieve what I want?

---

OT: Could you please add a newline between the code markers in the **Please paste the output** template?

**Comment by mathstuf** [comment]
This is a WebKit1 limitation. From the readme:

```
Adds a CSS file to pages when loaded. only supports one extra stylesheet at a time.
```

**Comment by GSI** [comment]
Clarified.

(I'm not sure, though, if "with this command" is proper English or if it should say "by this command" instead xD)
