### ISSUE TITLE
Cannot use keybindings, no status bar, etc on next

### ISSUE THREAD

**Issue by SirCmpwn** [uzbl/uzbl#261]
Please paste the output of `uzbl-core --bug-info` here:

```
sircmpwn@homura ~> uzbl-core --bug-info
Commit: v0.9.0-46-g85ca4b2
GTK compile: 3.20.3
GTK run: 3.20.3
WebKit compile: 2.12.0
WebKit run: 2.12.0
WebKit2: 1
libsoup compile: 2.54.0
libsoup run: 2.54.0
```

Just compiled+installed uzbl from the next branch. When running uzbl-tabbed, I see the tab bar, but not a status bar, and none of my keybindings work. When running uzbl-browser, I don't see the status bar and none of my keybindings work.

I've also noticed that it's creating its sockets in './= ', not in /tmp.

**Comment by SirCmpwn** [comment]
If I build uzbl-tabbed-next-git from the AUR, it [crashes on startup](https://sr.ht/6TnY.txt).

**Comment by keis** [comment]
Sounds like you might be using an old config

https://github.com/uzbl/uzbl/blob/next/UPGRADING.md

**Comment by SirCmpwn** [comment]
Yep, that was the issue. I still get the segfault when building from the AUR though, should I move that into another GH issue?

**Comment by keis** [comment]
Sure, please open that as a new one. To be able to help debug that we will need a traceback with debug symbols

**Comment by SirCmpwn** [comment]
Alright, I'll rebuild the package with debug symbols shortly. Thanks!

**Comment by SirCmpwn** [comment]
As an aside: working on bringing the changes I made to my old config into the new config, and I've noticed that the hint keys no longer work. No errors, the keybinding just doesn't do anything. The keys "fl" appear in the command prompt thing. Any ideas?

**Comment by keis** [comment]
on next running javascript on the page through the command is not supported (yet) which fl uses

**Comment by SirCmpwn** [comment]
Ah, fair.
