### ISSUE TITLE
Can't type unicode characters in command monde

### ISSUE THREAD

**Issue by everton1984** [uzbl/uzbl#273]
Hi,
I don't know if it's by design or by my own stupidity but I can't type unicode characters while in command mode which is sort of a nuisance because while searching stuff on duckduckgo or opening a url I sometimes need them. To be honest I can't even search for c++ because of the + sign. Since I can't find a configuration option to change this I kinda think it's a bug. Any help is welcome.

Regards,
E.

**Comment by keis** [comment]
Hi @everton1984 

gtk+ is all unicode these days so there should be no problem displaying any character as long as you have the font for it. So I'm guessing it's an issue with input rather than the presentation.

What version are you using (paste --bug-info)?
How are you trying to type these special symbols?
 - simple key press (aka printed on the keyboard)
 - dead keys (composing by sequence of keys)
 - mod keys (holding some key to change meaning of others)
What keyboard layout are you using?

**Comment by everton1984** [comment]
Hi @keis 
am I supposed to start uzbl with the command option --bug-info? I tried with no luck. If that's of any use I'm using the latest stuff from archlinux repo. I'm testing this under two types of keyboards one is BR-ABNT2 and the other US INTL. 

So the part about searching c++ on duckduckgo is probably my fault, I can type + on uzbl command line but the character is not escaped on the url (I'm using %s on cbind) so I don't get the result I'm expecting. What is the correct % I should be using on cbind?

The part about using ~ on a url, for example, is a dead key, while typing <dead_tilde> flashes (or something similar) and it cancels the command. 

My setup, if it matters, is Archlinux+xmonad on a Dell Vostro 1510 and a Lenovo Thinkpad T400, two unicode locales are setup en_US.UTF8 and pt_BR.UTF8, on the abnt keyboard I run 'setxkbmap br abnt2' and the us intl I run 'setxkbmap us intl'.

**Comment by keis** [comment]
if `uzbl-browser --bug-info` is not working you are most likely running a old version. Try to update and see if that helps.

i can confirm duckduckgo for `c++` is broken, I'll look into that

**Comment by everton1984** [comment]
Yeah you're right, just got the latest stuff here from github and the dead key problem is solved, thanks! C++ problem is possible to replicate. Do you want me to close this issue and open another one just for that? The title might be a bit misleading.

**Comment by keis** [comment]
Ok. great :)

And, yes, lets create another issue for the escape for ddg
