### ISSUE TITLE
uzbl-tabbed does not appear to receive (or relay?) MOD_RELEASE events

### ISSUE THREAD

**Issue by hofheinz** [uzbl/uzbl#274]
Hi,

First of all, this is great work!

I may have run into a problem with uzbl-tabbed: it seems that in command mode, modifiers (Ctrl, Mod1, etc.) are not cleared upon releasing the modifier key.

More precisely: start uzbl-tabbed, hit Ctrl, release Ctrl. Expected behavior: red `<Ctrl>` modifier message shows up in statusbar, then disappears again. Observed behavior: red `<Ctrl>` modifier message shows up and stays there. (It does get cleared upon a "lost window focus" X event, but not, e.g., upon pressing Escape.) This can lead to annoying situations when pressing some non-bound sequence like `<Mod1>l`, in which case a subsequent ":exit", Escape etc. does not reset things. (Instead, uzbl-tabbed waits for a longer sequence and can seemingly only be reset by forcing a clear-modifiers event, e.g., by switching to another X window and back.)

Curiously, uzbl-browser works just fine. Looking at the corresponding uzbl-core events (by connecting to the uzbl socket), it seems that uzbl-tabbed does not show MOD_RELEASE events, only MOD_PRESS events.

Please paste the output of `uzbl-core --bug-info` here:

```
Commit: v0.9.0-39-ga253f37
GTK compile: 3.20.3
GTK run: 3.20.3
WebKit compile: 2.4.11
WebKit run: 2.4.11
WebKit2: 0
libsoup compile: 2.54.1
libsoup run: 2.54.1
```

More info: OS is Debian, compiled from current git source (master branch, although "next" also appears to have the same issue) with GTK3 and Python3. Configuration is the default (shipped) one.

Is there a specific website which shows the problem?
No

If it is related to a crash on a website, do other WebKit-based browsers
exhibit the same symptoms? Other browsers include surf, midori, jumanji, dwb,
and sugar-browse.
xombrero appears to work fine (I guess this is uzbl-tabbed-specific, since uzbl-browser works just fine as well)

**Comment by keis** [comment]
Thanks for the report. this does indeed look broken. I'm not sure what colud be causing this as neither the xembed code or key press stuff has changed in a long while.

**Comment by hofheinz** [comment]
Thanks for your reply! I'd be happy to try to debug and hunt this down, but I'm not quite sure where to start. Let me know if I can help, or if you would like more specific information about the setup.

**Comment by keis** [comment]
did a git bisect with the 2012 version and it seems this was a regression in c1f60af60f82614f25ef77db25fb6684e61d252b

**Comment by keis** [comment]
A fix is in master now

**Comment by hofheinz** [comment]
Works now, great, thanks!

**Comment by mathstuf** [comment]
> it seems this was a regression in c1f60af

Indeed :) . Copy pasta at its best.
