### ISSUE TITLE
Character '+' is not correctly escaped with cbind %s

### ISSUE THREAD

**Issue by everton1984** [uzbl/uzbl#277]
This is the output of --bug-info
Commit: v0.9.0-41-gf05ef86
GTK compile: 3.20.4
GTK run: 3.20.4
WebKit compile: 2.4.11
WebKit run: 2.4.11
WebKit2: 0
libsoup compile: 2.54.1
libsoup run: 2.54.1

I tried with Youtube, Duckduckgo and IMDb, they all fail, here's the cbind commands I'm using

@cbind ddg<DuckDuckGo:>_    = uri https://duckduckgo.com/?q=%s
@cbind Youtube<Youtube:>_ = uri https://www.youtube.com/results?search_query=%s
@cbind Imdb<IMDb:>_ = uri http://www.imdb.com/find?ref_=nv_sr_fn&q=%s&s=all

The weird thing is that AUR works correctly, here is it's cbind

@cbind Aur<AUR:>_ = uri https://aur.archlinux.org/packages/?O=0&K=%s

**Comment by everton1984** [comment]
Looks like %s isn't the right way to add a search query for search engines and this fact is reflected on the upstream config example. The correct way is through encodeURIComponent. I fixed the example config file on my uzbl repo, everton1984/uzbl. What's the procedure to merge here? or should I send a patch?

**Comment by keis** [comment]
Ok, cool :)

Open a pull request on here and reference this issue number
