### ISSUE TITLE
Can't paste in command mode 

### ISSUE THREAD

**Issue by everton1984** [uzbl/uzbl#280]
Please paste the output of `uzbl-core --bug-info` here:
Commit: v0.9.0-41-gf05ef86
GTK compile: 3.20.4
GTK run: 3.20.4
WebKit compile: 2.4.11
WebKit run: 2.4.11
WebKit2: 0
libsoup compile: 2.54.1
libsoup run: 2.54.1

I can't type Ctrl+v in command mode, or better saying, I can, but it outputs nothing. I'm using xclip, tried clipboard and primary, no luck. I think this is somewhat related to the fact that all mod-keys get cancelled in command mode. Maybe this is just a configuration issue but I can't find an option to change this behaviour.

**Comment by keis** [comment]
There is no `<Ctrl>v` binding in the example config, it works with forward_keys because then it triggers the builtin webkit handler.

Could you explain what you are trying to do and how you are trying to do it?

**Comment by everton1984** [comment]
Hi @keis ,
I'm trying to copy the contents of 'xclip -selection clipboard' onto a search for duckduckgo for example, or paste part of a url onto the uri command. I want to be able to paste stuff to the current command I'm typing in the command mode. I don't really care if it's Ctrl+v (although I kinda think this should be the case)..

**Comment by GSI** [comment]
@everton1984, try `Shift+Insert`.

**Comment by everton1984** [comment]
@GSI ,
is there a way to configure this on uzbl's config file? I can't even try this combination because my keyboard does not have the Insert key.

**Comment by keis** [comment]
All key bindings are defined in the config file. You can copy the Shift+Insert binding and change it to Ctrl+v if you want to.

```
@bind <Ctrl>v = spawn_sh 'echo "event INJECT_KEYCMD $(xclip -o | sed s/\\\@/%40/g)" > "$UZBL_FIFO"'
```

**Comment by everton1984** [comment]
Oh, awesome. Thanks.
