### ISSUE TITLE
Can't build on latest Raspbian Release

### ISSUE THREAD

**Issue by jameskirsop** [uzbl/uzbl#281]
This isn't a problem explicitly with Uzbl, but I'm pulling my hair out.

I've installed all the same (but newer) libraries as a previous version of Raspbian but I'm getting stuck.

I can see webkit.h located in /usr/include/webkitgtk-3.0/webkit/, but I'm assuming some environment variable is broken/not set...

```
pi@raspberrypi:~/uzbl-next $ make
Requested 'gio-2.0 >= 2.44' but version of GIO is 2.42.1
Requested 'gio-2.0 >= 2.44' but version of GIO is 2.42.1
cc -std=c99  -ggdb -W -Wall -Wextra -pthread -Wunused-function -DG_DISABLE_DEPRECATED -D_XOPEN_SOURCE=500 -DARCH=\"armv7l\" -DCOMMIT=\"v0.9.0-43-g1b54510\" -DLIBDIR=\"/usr/local/lib/uzbl\" -DHAVE_LIBSOUP_CHECK_VERSION  -c -o src/uzbl-core.o src/uzbl-core.c
In file included from src/uzbl-core.h:4:0,
                 from src/uzbl-core.c:30:
src/webkit.h:4:27: fatal error: webkit/webkit.h: No such file or directory
 #include <webkit/webkit.h>
                           ^
compilation terminated.

**Comment by keis** [comment]
pkg-config is failing so you don't get any include flags. The error message is terrible because we try to compile anyway.

Anyway, raspbian is not supported on master for now (0.9.0 should be fine) unless you can find a glib-gio-2.44 to install

**Comment by mathstuf** [comment]
I have a branch to detect when the prereqs are missing and error out, but it seems GitHub is having some troubles updating the webpage with my new branch, so I can't open a PR.

**Comment by mathstuf** [comment]
I have a branch to detect when the prereqs are missing and error out, but it seems GitHub is having some troubles updating the webpage with my new branch, so I can't open a PR.

**Comment by keis** [comment]
@mathstuf I can see the branch now :) looks like a pretty good way of making it easier to notice the relevant error message

**Comment by jameskirsop** [comment]
FYI, I'm able to build the latest master release on the testing version of raspbian now.

Probably worth closing this off now - I've got a number of other issues but they're not specifically related to this issue.
