### ISSUE TITLE
Problem with default configuration Ctrl+c bind

### ISSUE THREAD

**Issue by everton1984** [uzbl/uzbl#283]
Please paste the output of `uzbl-core --bug-info` here:
GTK compile: 3.20.3
GTK run: 3.20.4
WebKit compile: 2.4.11
WebKit run: 2.4.11
WebKit2: 0
libsoup compile: 2.54.0
libsoup run: 2.54.1

Just type Ctrl+c with a text selected, nothing happens, this is the cbind I have, taken from latest git repo:

@cbind <Ctrl>c = sh 'echo '\@< window.getSelection().toString().replace(/'/g, "\\'"); >\@' | xclip -selection clipboard -i'

I don't know the super-clean correct approach but my fix involves actually changing to spawn command and calling an external script. I kept trying to use spawn_sh but no cigar.

I can make a pull request if adding the external script really sounds like a reasonable solution.

**Comment by keis** [comment]
hmm, looks like some problems with escaping it would have to look like this now.
```
@cbind <Ctrl>c = spawn_sh 'echo \\\'\@< window.getSelection().toString().replace(/\'/g, "\\\\\'"); >\@\\\' | xclip -selection clipboard -i'
```

But then it still breaks on newlines, But I think it has always done that.

**Comment by keis** [comment]
using base64 looks like a better aproach, could you test if this works for you?

```
@cbind <Ctrl>c = spawn_sh 'echo \@< btoa(window.getSelection().toString()) >\@ | base64 -d | xclip -selection clipboard -i'
```

**Comment by everton1984** [comment]
Works perfectly here.

**Comment by keis** [comment]
Ok. Thanks for helping me test it out. Applied to master :)
