### ISSUE TITLE
How do I run JS in the page context via socket, and return results?

### ISSUE THREAD

**Issue by anko** [uzbl/uzbl#285]
I'm trying to make my "open this textarea in an external editor"-script work in the newer version of uzbl, since Arch Linux packagers seem to have decided that shall be the norm now.

My script currently connects to the `$UZBL_SOCKET`, sends a `js` command which extracts the text contents of the focused textarea, and expects to receive back on the other half of the socket duplex connection what that JavaScript returns.

Instead, while the JS seems to run, I can't see any way in which the return stream delivers its return value.

How should I be doing this?

---

`uzbl-core --bug-info`:

```
Commit: UNKNOWN
GTK compile: 3.20.3
GTK run: 3.20.4
WebKit compile: 2.4.11
WebKit run: 2.4.11
WebKit2: 0
libsoup compile: 2.54.0
libsoup run: 2.54.1
```

**Comment by keis** [comment]
The example scripts use a echo into `socat - "unix-connect:$UZBL_SOCKET"` and then pipe that into something dealing with the result. Sounds like you're doing the same so it should work.

You say the javascript seems to run, can you confirm that somehow?

**Comment by mathstuf** [comment]
Javascript in WebKit2 cannot run within the page since we haven't hooked it all up properly yet (see #249). If it does, Arch has a patch we'd like to have :) .

**Comment by keis** [comment]
This is not webkit2 though

**Comment by mathstuf** [comment]
Oh, I somehow read "next" in the first sentence of the report. Missed the bug info block.

**Comment by keis** [comment]
Closing this, re-open if you're still having issues
