### ISSUE TITLE
Late LINK_UNHOVER events (next branch only)

### ISSUE THREAD

**Issue by hofheinz** [uzbl/uzbl#287]
Hi,

In the current next branch with WebKit2, uzbl-core seems to get/relay LINK_UNHOVER events only right before the next LINK_HOVER event. More precisely: when I run
  `uzbl-core -p -c conf google.com`
with a configuration `conf` that contains only the line
  `set status_format \@SELECTED_URI`
then hovering over a link causes a LINK_HOVER event on stdout, and that link appears in the status bar. However, when moving the pointer to a free space on screen, there is no LINK_UNHOVER event, and the link does not disappear from the status bar. (With WebKit1, there is an immediate LINK_UNHOVER event, and the link disappears.) Later on, when hovering onto the next link, there is a LINK_UNHOVER `old-uri`, and then a LINK_HOVER `new-uri` event.

This behavior is a bit annoying, since it means that `@SELECTED_URI` is essentially always set (and sometimes to an outdated value). I guess this is not intended (also since this does not occur with WebKit1).

Output of `uzbl-core --bug-info`:
```
Commit: v0.9.0-72-gb6b9235
GTK compile: 3.20.4
GTK run: 3.20.4
WebKit compile: 2.12.3
WebKit run: 2.12.3
WebKit2: 1
libsoup compile: 2.54.1
libsoup run: 2.54.1
```

**Comment by hofheinz** [comment]
Looking at `gui.c`, and in particular at `send_hover_event` there, it seems that that LINK_UNHOVER event is generated upon the next LINK_HOVER event from webkit. So maybe uzbl doesn't receive any LINK_UNHOVER events at all?

**Comment by keis** [comment]
it's called from `mouse_target_cb` where we have an early return if it's not hovering a link. Assuming that function is actually called properly we should only need to make sure we call send_hover_event with empty strings.

**Comment by hofheinz** [comment]
Yes, that seems to work! I understand that in the WebKit1 version, all of this worked differently (with different callbacks), so the `master` is not affected. I prepared a (very minimalistic) pull request with what you suggested (but beware, my understanding of all the callback stuff, and in particular when they happen, is rather limited).

**Comment by hofheinz** [comment]
Closing this then (issue seems solved).
