### ISSUE TITLE
Response to Socket is very slow

### ISSUE THREAD

**Issue by AKuederle** [uzbl/uzbl#290]
Please paste the output of `uzbl-core --bug-info` here:

```
Commit: UNKNOWN
GTK compile: 3.20.3
GTK run: 3.20.6
WebKit compile: 2.4.11
WebKit run: 2.4.11
WebKit2: 0
libsoup compile: 2.54.0
libsoup run: 2.54.1

```

I was trying to control the browser using a script talking to the socket, as described in the example. However, it takes the browser up to 10s to react to any input given this way. Interestingly, the dmnu commands the browser uses itself, work fine.

Is there anything i am overlooking? Is the socket blocked in some way or has some kind of delay set?

**Comment by keis** [comment]
Could you paste the script you're trying to use. There is nothing special being done by the example scripts.

**Comment by mathstuf** [comment]
> Commit: UNKNOWN

Hrm. How did you build this?

**Comment by AKuederle** [comment]
That's the package from the arch community repo. 
BTW. I still don't know, what caused the problem, but I build the next branch from the Air and it seems to work. Therfore, I think it might be related to the arch package for some reason.

**Comment by keis** [comment]
Hmm. looks like UNKNOWN is actually what you get when building from the released tarball as misc/hash.sh was only fixed afterwards.
