### ISSUE TITLE
CSS3 animations not supported in Raspbery pi 2

### ISSUE THREAD

**Issue by navaneetharaopy** [uzbl/uzbl#292]
```
** (uzbl-core:1372): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Commit: v0.9.0
GTK compile: 3.14.5
GTK run: 3.14.5
WebKit compile: 2.4.1
WebKit run: 2.4.1
WebKit2: 0
libsoup compile: 2.48.0
libsoup run: 2.48.0
```

Compiled new uzbl browser in raspbery pi 2 (raspbian jessie OS) and found CSS3 animations are not supported. But same code compiled in raspbery pi B CSS3 animation works.

Is there any extra flag/package that need to be included while compile?

**Comment by keis** [comment]
That kind of feature would really only be down to the libwebkitgtk version and compile flags. Is there any difference between these two installs in webkit version used?

**Comment by navaneetharaopy** [comment]
used following command to compile
 ```sudo apt-get -y install libwebkitgtk-3.0-dev```
```cd /home/pi/```
```git clone git://github.com/uzbl/uzbl.git```
```cd uzbl```
```git checkout tags/v0.9.0```
``` make ```
``` sudo make install ```
```sudo ln -s /usr/local/bin/uzbl-browser /usr/local/bin/uzbl``` 
```sudo apt-get -y install python3-pip```
```sudo pip-3.2 install six```

**Comment by navaneetharaopy** [comment]
All the versions are same(same SD card image runs on both). Also i noticed if i install uzbl using ```sudo apt-get install uzbl``` , the CSS transition also works in pi 2

**Comment by keis** [comment]
ok. that's weird. My guess would be you are getting the 2012 version apt. Could you try building that from git and see if that works?

**Comment by navaneetharaopy** [comment]
Just built uzbl from ```Commit: 2012.05.14``` and that works. Even the current one (0.9.0) works in raspbery pi B+(armv6) , but does not work on pi 2 (armv7). Any clues?

**Comment by keis** [comment]
Are you using the same config for both? because a lot of options and even syntax has changed in 0.9. You can try the browser in a clean environment with `make test-uzbl-browser-sandbox`

**Comment by navaneetharaopy** [comment]
Yes.
Any special flag(in Makefile) to be included while compile?

**Comment by mathstuf** [comment]
For the sandbox? No. It should set up a sandbox to test what is in the git repo exactly.

**Comment by jameskirsop** [comment]
FWIW, I'm having a similar problem with 0.9.0 on two Pi2's. One is running Jessie, the other is running stretch (testing).

On my Pi's I'm unable to render Google Maps, as well as some SVG's that are generated via javascript.

It's difficult for me to test with the sandbox because my Uzbl instances are spawned from scripts that run on boot rather than from me manually launching them.

**Comment by mathstuf** [comment]
Do other OpenGL-ish things work? Other browsers?

**Comment by navaneetharaopy** [comment]
@mathstuf  I think this is not related to OpenGL , Because the same sd card when used in Raspberry pi b+ (armv6) it works. 
You mentioned about uzbl config, which file you are referring to?
Animation event firing problem occurs in raspberry pi 3 & raspberry pi 2  both belong to ARMv7.
It would be great if you mention some dependency packages to be installed before compile.
Currently i install  following package with command `sudo apt-get -y install libwebkitgtk-3.0-dev`. Is it the right package ?

**Comment by mathstuf** [comment]
For `master`, yes, I think that is the right package. Uzbl checks for all dependencies before the build and should error out if it can't find any. The config file is `~/.config/uzbl/config`.

**Comment by jameskirsop** [comment]
I've just picked this back up again and asked the folks over at webkitgtk for some assistance. They've requested I try building against a more recent release than the version that is packaged for jessie (webkitgtk 2.4).

I've installed libwebkit2gtk-4.0 and the relevant related packages, to get 2.14 (not quite 2.16, but a much newer version).

Now when I try to `make build` the latest next branch I'm getting the following
```
pip3 install -I --prefix=/usr/local --install-option="" dist/uzbl-0.9.1+181.g8c42324-py3-none-any.whl

Usage:   
  pip install [options] <requirement specifier> ...
  pip install [options] -r <requirements file> ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --prefix
Makefile:252: recipe for target 'install-event-manager' failed
make: *** [install-event-manager] Error 2
```

and when I try to use the correct pip syntax:
`pip install --install-option="--prefix=/usr/local" dist/uzbl-0.9.1+181.g8c42324-py3-none-any.whl`

I get:
```
/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py:194: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
uzbl-0.9.1+181.g8c42324-py3-none-any.whl is not a supported wheel on this platform.
```

**Comment by jameskirsop** [comment]
In an effort to try and get this working, I've compiled against the packages available for the stretch release of raspbian - which should be released as stable soon.

When doing so, I'm seeing the following errors when running uzbl from a terminal window:

```
** (WebKitWebProcess:1617): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

** (WebKitWebProcess:1617): WARNING **: Error writing message header: Error writing to file descriptor: Bad file descriptor

(WebKitWebProcess:1617): Gtk-WARNING **: Failed to parse /home/pi/.config/gtk-3.0/settings.ini: Key file does not have group 'Settings'
awk: cannot open /home/pi/.local/share/uzbl/cookies.txt (No such file or directory)
awk: cannot open /home/pi/.local/share/uzbl/session-cookies.txt (No such file or directory)

(uzbl-core:1597): Gtk-WARNING **: Failed to set text '<markup><span font_family="monospace"><span foreground="#586e75">proxy:</span> <span foreground="#2aa198"></span>  <span foreground="#586e75">uri:</span> <span foreground="">http://uzbl.org/doesitwork/v0.9.1-181-g8c423242</span></span></markup>' from markup due to error parsing markup: Value of 'foreground' attribute on <span> tag on line 1 could not be parsed; should be a color specification, not ''
```

I'm assuming these are webkit problems, but can I get confirmation on this? I'm expecting the gtkwebkit folks to refer me to a more recent release (2.16 instead of 2.14 which seems to be the one shipping with stretch), which means I might be back to square one.

**Comment by keis** [comment]
Those error messages are from uzbl but probably not related to the rendering problem. You could try running uzbl-core without a config `uzbl-core -c /dev/null` and see if you still get any errors.

**Comment by jameskirsop** [comment]
FWIW, I've just compiled uzbl/next against the latest available webkit2gtk packages for stretch and it appears this problem has been resolved.

I've got a seperate problem for CSS3 fonts not loading on this newly compiled version, but that's probably not related to this issue.
