### ISSUE TITLE
Multi language website shows English website, I want Dutch language

### ISSUE THREAD

**Issue by enieuwenhuis** [uzbl/uzbl#303]
I have installed Screenly ose en configured my raspberry pi locales with nl_NL.UTF-8. (That is Dutch). Screenly OSE uses Uzbl as webbrowser

But a website shows the English website when it is multi language. When I visit this website from a deskop browser, it is in Dutch language.
How can I configure Uzbl that it will take the Dutch language? Or what should I do to fix this?

Thanks.

**Comment by mathstuf** [comment]
There's the `accept_languages` variable ([docs](https://github.com/uzbl/uzbl/blob/master/README.md#page-1)). Can you see what the `Accept-Languages` HTTP header is from the inspector?

**Comment by enieuwenhuis** [comment]
I'm sorry, but I don't understand what you mean with "the inspector".

**Comment by keis** [comment]
there is a builtin webinspector in webkit. you can get to it by either right clicking and selecting inspect element or using the uzbl command "inspector show"

**Comment by enieuwenhuis** [comment]
Thank you.
I don't find Accept-Languages in the HTTP header.

**Comment by keis** [comment]
Hmm I can't find headers at all in the inspector.

could you try adding this to your config
```
set http_debug headers
set accept_languages nl-NL
```

this will show headers on the terminal and also should be getting you dutch.

**Comment by mathstuf** [comment]
Headers should be shown in the `Timeline` section when you click on a network request, the `Request Headers` box is on the right.

**Comment by mathstuf** [comment]
I do not see the `Accept-Languages` header at all being sent; I suspect it is a webkitgtk thing, but checking webkit2 would be something to do.

**Comment by keis** [comment]
setting `accept_languages` does work for me. In both wk1 and wk2
