### ISSUE TITLE
New release of the 0.9 series

### ISSUE THREAD

**Issue by keis** [uzbl/uzbl#314]
We have collected quite a few patches on top of the last release on master again. I think it's time to cut 0.9.1

**Comment by mathstuf** [comment]
Sounds good to me.

**Comment by keis** [comment]
0.9.1 is released :balloon: :tada:

**Comment by Dieterbe** [comment]
woohoo!

**Comment by GSI** [comment]
When trying to install the Arch packages created from the repo, I get:

    error: failed to commit transaction (conflicting files)
    /usr/share/uzbl/docs/KEYBINDINGS.md exists in both 'uzbl-core-master-git' and 'uzbl-browser-master-git'
    Errors occurred, no packages were upgraded.

I suspect that's something to be fixed directly in the sources (?)

**Comment by mathstuf** [comment]
No, that's a packaging error in the Arch package (`KEYBINDINGS.md` belongs only in the browser subpackage).
