### ISSUE TITLE
Can't hide status bar

### ISSUE THREAD

**Issue by Epy** [uzbl/uzbl#318]
Hello
I'm trying to make a kiosk with a Raspberry PI2, it's almost working:
In the conf file I tried

> set status_bar=0

and 

> set  status_bar 0

 (and 1 and 2 ...) like I found in this github
but the bar is still showing.

I'm using a launch command line in .xsession: 

> pi@raspberrypi:~ $ cat .xsession 
> #!/bin/bash
> DISPLAY=:0 xset s off -dpms &
> URL="https://www.nayuki.io/res/full-screen-clock-javascript/full-screen-clock-24hr.html"
> uzbl -u $URL -c /home/pi/uzbl.conf &
> exec matchbox-window-manager  -use_titlebar no

the uzbl.conf file: 

> set show_status 0
> set geometry=maximized
> set status_background=#000000

Maximize and background color are working, but the color is a workaround because the real page I want to display has multiple divs of multiple colors all over and will change or scroll (and there is still some info in this status bar)

uzbl-core:

> pi@raspberrypi:~ $ DISPLAY=:0 uzbl-core http://duckduckgo.com --bug-info
> Failed to spawn child process: /home/pi/.local/share/uzbl:/share/uzbl/examples/data:scripts/load_cookies.sh not found
> Failed to spawn child process: /home/pi/.local/share/uzbl:/share/uzbl/examples/data:scripts/load_cookies.sh not found
> Failed to spawn child process: /home/pi/.local/share/uzbl:/share/uzbl/examples/data:scripts/scheme.py not found
> Failed to spawn child process: /home/pi/.local/share/uzbl:/share/uzbl/examples/data:scripts/scheme.py not found
> Failed to spawn child process: /home/pi/.local/share/uzbl:/share/uzbl/examples/data:scripts/scheme.py not found
> Failed to spawn child process: /home/pi/.local/share/uzbl:/share/uzbl/examples/data:scripts/scheme.py not found

I'm on raspbian jessie

> pi@raspberrypi:~ $ sudo apt-cache showpkg uzbl
> Package: uzbl
> Versions: 
> 0.0.0~git.20120514-1.1+b1 

Thanks

**Comment by mathstuf** [comment]
That's a really old version of uzbl. IIRC, there was a bug where the status bar setting did nothing if the status bar object doesn't exist which is true before the UK is shown.

**Comment by Epy** [comment]
Ow, ok. I thought it could be a version problem but I hoped Raspbian had a decent one.
I'll install a new version and try again

Thanks :)

**Comment by mathstuf** [comment]
We went about 3 years without a release. 0.9 should be available in backports, but the `CHANGES.md` file is very important there if you're not starting from scratch.

**Comment by jmcphail** [comment]
Similar situation, built uzbl and glib packages from source.

`root@pi:~# DISPLAY=:0 uzbl-core --bug-info`

`** (uzbl-core:1215): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files`
`Commit: v0.9.1-4-g1de304b`
`GTK compile: 3.14.5`
`GTK run: 3.14.5`
`WebKit compile: 2.4.1`
`WebKit run: 2.4.1`
`WebKit2: 0`
`libsoup compile: 2.48.0`
`libsoup run: 2.48.0`

Any suggestions?  Status bar still visible after setting show_status=0

**Comment by mathstuf** [comment]
The new syntax is `set show_status 0` (without the `=`).

**Comment by Psychokiller1888** [comment]
The status bar is still visible, on the bottom part of the screen, displaying the page title and the address, using either

set show_status 0 OR
set_show_status = 0

on a raspberry pi

**Comment by Psychokiller1888** [comment]
Only works by sending a cmd 'set show_status=0' while uzbl running. Setting it in the configs won't do anything

**Comment by mathstuf** [comment]
If you're on an old enough version, there was a bug where the status bar wasn't created until after the config was read.

**Comment by mathstuf** [comment]
See commit 529538668 for the fix.

**Comment by Psychokiller1888** [comment]
I have installed it through apt-get on my raspberry pi 3 and it is not working. How do I get your version that should be working?
