### ISSUE TITLE
src/variables.c:453: bad test ?

### ISSUE THREAD

**Issue by dcb314** [uzbl/uzbl#320]
src/variables.c:453]: (warning) Logical disjunction always evaluates to true: EXPR != 0 || EXPR != ' '.

Source code is

    if (url != NULL || *url != 0 || *url != ' ')
        soup_uri = soup_uri_new(url);

Maybe better code

    if (url != NULL && *url != 0 && *url != ' ')
        soup_uri = soup_uri_new(url);

**Comment by mathstuf** [comment]
Indeed, this would be a bug. Thanks.

**Comment by keis** [comment]
Looks like this was fixed in ad64608c38585c6dd4d1d0d2e149ca9c352f675e

**Comment by mathstuf** [comment]
Indeed. That is in 0.9. @dcb314 Please update.

**Comment by dcb314** [comment]
>Please update.

Good advice. Code I commented on is in Fedora rawhide. Perhaps
time for those folks to update to something more recent ?
