### ISSUE TITLE
fi not working

### ISSUE THREAD

**Issue by andmarti1424** [uzbl/uzbl#325]
Hello. 
I have installed 1:0.9.0-1 version of uzbl-browser in Arch, but I am having problems with the fi command.
Its suppose to place cursor over the first input field and enter insert mode, but no action is done.
no error or output shown.

I thought to follow this https://www.uzbl.org/wiki/go-input,
so I edit those files, but with no success either. Same behaviour. the following error is logged in terminal though:
socat [3090] E connect(5, AF=1, "<anon>", 2): invalid argument.

NOTE: test page is google.com and other commands such as 'fl' is working great.

Thanks!!

**Comment by keis** [comment]
Hmm. that javascript looks to have been broken for a while in master. I'll look into it

The script on the wiki is outdated as the socket path etc is no longer given as arguments but should be read from the ENV.
