### ISSUE TITLE
Misbehaving status bar on wayland

### ISSUE THREAD

**Issue by keis** [uzbl/uzbl#327]
Please paste the output of `uzbl-core --bug-info` here:

```
Commit: v0.9.1-81-g24342e7
GTK compile: 3.22.2
GTK run: 3.22.2
WebKit compile: 2.14.1
WebKit run: 2.14.1
WebKit2: 1
libsoup compile: 2.56.0
libsoup run: 2.56.0
```

This happens with both the example config and with `-c /dev/null` (but it's not as visible as only the text is flowing out)

**Comment by mathstuf** [comment]
For clarity, what is the behavior on wayland (it will be a while before I really get to use it).

**Comment by keis** [comment]
![statusbar](https://cloud.githubusercontent.com/assets/125062/20893431/0c79ecfa-bb12-11e6-91ea-aed9b2f07c26.png)

d'oh was meaning to attach this screenshot.

**Comment by mathstuf** [comment]
Um, yeah, I'll call that odd :) .

**Comment by keis** [comment]
Looks like this issue got resolved by some change elsewhere in the stack. Working both on the commit noted here and in next.

Closing.
