### ISSUE TITLE
Firejail support (uzbl and uzbl-event-manager)

### ISSUE THREAD

**Issue by GSI** [uzbl/uzbl#335]
On first invocation, **uzbl-browser** starts just fine within firejail (profile at https://github.com/netblue30/firejail/pull/1060).

However, it's impossible to start a second instance since **uzbl-event-manager** is already "trapped" (jailed) by the first one:

    uzbl-event-manager: ERROR: event manager already started with pid 12

Any idea where to best tackle that issue?

**Comment by GSI** [comment]
I'm working around the issue by using a clean ~/.cache/uzbl directory upon any firejail uzbl-browser invocation.

To my knowledge, that will start a new event manager for every uzbl-browser instance.

* What are the risks of this?
* For example, can personal files like cookies and the like be messed up by that?

**Comment by keis** [comment]
what is the intended result? do you want them to have independent EMs or share one.

the bug here is either trying to start the em when there already is one (is the sandbox hiding this from uzbl-browser?) or that it's not possible to run two independent ems (are we not getting  separate runtime dirs from the sandbox?)

**Comment by keis** [comment]
Yep. starting with a clean cache dir should work (it's actually weird that it does we really should be using $XDG_RUNTIME_DIR). If running multiple EMs you will not get a merged view of what cookies you have neither on disk or in runtime.

**Comment by GSI** [comment]
Ok, I'll PR (to firejail) a profile with separate cache dirs then.

Out of curiousity and for my understanding: Which advantages would it have to run just one event manager for multiple uzbl's?

**Comment by keis** [comment]
One of the jobs of the event manager is to synchronise state between instances in particular command history and cookies. So when one uzbl instance receives a cookie it will send an event and the reaction to that is to add that cookie to all other instances.

**Comment by keis** [comment]
I opened #336 to change the EM to use the runtime dir. Would that break the jail somehow?

**Comment by GSI** [comment]
Each and every uzbl instance started in the firejail gets the same ID (8, on my machine).

So there is an issue already: Fifo and Socket file names are not unique:
`/run/user/1000/uzbl/uzbl_(fifo|socket)_8`

Not sure how to handle that. I doubt there is a way to get the firejail process ID and use that one for example (e.g. `/run/user/1000/uzbl/21621/uzbl_(fifo|socket)_8`), or is there?

**Comment by mathstuf** [comment]
You can pass `--named NAME` to name an instance; by default it uses the X window ID (which is probably why each is the same).

**Comment by GSI** [comment]
I want to make sure to open any new **uzbl-browser** windows within the same firejail, as otherwise I'll be asked to enter my password store password with every new instance.

Currently I do `echo 'event REQ_NEW_WINDOW' > /run/user/1000/uzbl/uzbl_fifo_8`, but as soon as the last uzbl window is closed, this fails to work.

*Is there any way to run a uzbl base process always in the background without an X window?*

I would then run such a process upon startup and **REQ_NEW_WINDOW** whenever needed.

**Comment by mathstuf** [comment]
> Is there any way to persistently run a uzbl base process in the background without an X window?

Currently, no.

**Comment by keis** [comment]
But you don't need a full uzbl-core instance to launch new instances. You could put a small launcher reading from a fifo as the main process of the sandbox.

```
fifo=$XDG_RUNTIME_DIR/open-uzbl
test -p $fifo || mkfifo $fifo

while read uri < $fifo; do
    uzbl-browser $uri &
done
```

**Comment by GSI** [comment]
Genius! :+1: 

I noticed another issue: When running in firejail, downloads fail with the following message, although the downloads-directory is accessible:

```
** (uzbl-core:27667): CRITICAL **: SoupMessage* webkit_network_response_get_message(WebKitNetworkResponse*): assertion 'WEBKIT_IS_NETWORK_RESPONSE(response)' failed
```

**Comment by mathstuf** [comment]
Fun. We don't call that function unless `WEBKIT_IS_NETWORK_RESPONSE` passed.

**Comment by keis** [comment]
Oh, right. I remember someone talking about this on IRC before. Probably not related to firejail. Was it using the `download` command?

**Comment by GSI** [comment]
Since #346 is unrelated, I think firejail-support is good so far.
