### ISSUE TITLE
Use $XDG_RUNTIME_DIR for event-manager socket etc

### ISSUE THREAD

**Issue by keis** [uzbl/uzbl#336]
Currently the event-manager is using ~/.cache/uzbl for storing the socket and the pid but $XDG_RUNTIME_DIR is better suited for this and is what we're using for uzbl-core

It usually resolves to something like /run/user/1000 (systemd convention I think)

We should also set a fallback in uzbl-browser (tempdir with uid under /tmp?)

**Comment by mathstuf** [comment]
Yes, it should be preferred. I use it locally; I'll look at getting a PR up.
