### ISSUE TITLE
error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by l29ah** [uzbl/uzbl#366]
```
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
```

**Comment by mathstuf** [comment]
Why do you want a wheel? What's the use case? The event manager package isn't really meant for use outside of uzbl itself and has no versioning policy other than "what Uzbl wants or needs".

**Comment by l29ah** [comment]
On Sun, Apr 02, 2017 at 09:22:59AM -0700, Ben Boeckel wrote:
> Why do you want a wheel? What's the use case? The event manager package isn't really meant for use outside of uzbl itself and has no versioning policy other than "what Uzbl wants or needs".

It's pulled as a dep of uzbl-browser in Makefile.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by keis** [comment]
mea culpa, I thought wheel was part of the default python install when I switched to using wheel dist as a build step.

You'll need the python3-wheel package (name might differ depending on distro)

**Comment by l29ah** [comment]
On Sun, Apr 02, 2017 at 11:55:59PM -0700, David Keijser wrote:
> You'll need the python3-wheel package (name might differ depending on distro)

It did the trick, thanks.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments
