### ISSUE TITLE
[minor] Trailing spaces on bookmark lines

### ISSUE THREAD

**Issue by xelxebar** [uzbl/uzbl#388]
## Overview

This is extremely minor, but I noticed that my bookmark file has trailing spaces on each of its lines.

## Cause

It looks like this is coming from the following line in `examples/data/scripts/insert_bookmark.sh`:

    readonly sorted_uniq_tags="$( print "$tags" | tr ' ' '\n' | sort -u | tr '\n' ' ' )"

Since `sort` appends a newline at the end of output, the final `tr` in the pipeline is converting that into a space.

## A Fix

Here's a braindead munge to fix this:

```
diff --git a/examples/data/scripts/insert_bookmark.sh b/examples/data/scripts/insert_bookmark.sh
index b4506a3e..36da1ed3 100755
--- a/examples/data/scripts/insert_bookmark.sh
+++ b/examples/data/scripts/insert_bookmark.sh
@@ -38,7 +38,8 @@ fi
 readonly tags
 
 # Remove duplicate tags (also sorts)
-readonly sorted_uniq_tags="$( print "$tags" | tr ' ' '\n' | sort -u | tr '\n' ' ' )"
+sorted_uniq_tags="$( print "$tags" | tr ' ' '\n' | sort -u | tr '\n' ' ' )"
+readonly sorted_uniq_tags="${sorted_uniq_tags%% }"
 
 # Put the tags in the file
 print "$url	$title	$sorted_uniq_tags\n" >> "$UZBL_BOOKMARKS_FILE"
```

**Comment by mathstuf** [comment]
Is `%%` valid POSIX shell? Also, `sorted_uniq_tags` should be `readonly`. Please submit a PR.

Note that there will still be a trailing tab due to:

```sh
print "$url	$title	$sorted_uniq_tags\n" >> "$UZBL_BOOKMARKS_FILE"
```

**Comment by xelxebar** [comment]
Yes, `%%` is in the POSIX standard. You can see it a little down the page [here][1]. More importantly, perhaps, you can also see it in the `dash` manual.

`sorted_uniq_tags` is still `readonly`, my diff is just setting that on the second line.

Really? I figured a one-liner like this isn't worth the bother of a whole PR.

[1]:http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02

**Comment by mathstuf** [comment]
D'oh, missed that.

> Really? I figured a one-liner like this isn't worth the bother of a whole PR.

You already have it patched somewhere in Git. Rather than me copy/pasting the contents into a file, doing Git stuff and making a PR myself, you're at least two steps ahead.

**Comment by xelxebar** [comment]
PR request done.

Also, it seems your last comment slid in before I finished the ninja edit of my previous comment.
