### ISSUE TITLE
Javascript in binding not getting executed

### ISSUE THREAD

**Issue by nemanjan00** [uzbl/uzbl#391]
```
Commit: v0.9.1-95-g3a4c70ad
GTK compile: 3.22.7
GTK run: 3.22.21
WebKit compile: 2.14.3
WebKit run: 2.16.6
WebKit2: 1
libsoup compile: 2.56.0
libsoup run: 2.58.2

```

This is my cmd binding: 

```
@cbind  fl*  = spawn @scripts_dir/follow.sh \@< uzbl.follow.followLinks("\@follow_hint_keys", "%s", 'click') >\@
```

Basicaly, default one... 

What happends is uzbl.follow.followLinks never gets executed and script gets called with no arguments.

**Comment by keis** [comment]
I think the version you got is before the patches to fix javascript @<expansion@> landed. Could you try updating?

**Comment by nemanjan00** [comment]
It is latest version in arch community repo. I can try to build.

**Comment by nemanjan00** [comment]
I am two hours into compiling webkitgtk... 

This is not maintainable...

**Comment by keis** [comment]
Recompiling webkitgtk is not required and it's a massive build. You just need the latest sources of uzbl

**Comment by nemanjan00** [comment]
AUR package does recompile webkitgtk

**Comment by nemanjan00** [comment]
```
In file included from src/uzbl-core.h:4:0,
                 from src/uzbl-core.c:30:
src/webkit.h:4:10: fatal error: webkit/webkit.h: No such file or directory
 #include <webkit/webkit.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

This is error I get when i clone and run make...

**Comment by keis** [comment]
What's the first error you get? it's probably going to be from pkg-config

**Comment by nemanjan00** [comment]
```
Package webkitgtk-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `webkitgtk-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'webkitgtk-3.0' found
Package javascriptcoregtk-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `javascriptcoregtk-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'javascriptcoregtk-3.0' found
Package webkitgtk-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `webkitgtk-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'webkitgtk-3.0' found
Package javascriptcoregtk-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `javascriptcoregtk-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'javascriptcoregtk-3.0' found
cc -std=c99  -ggdb -W -Wall -Wextra -pthread -Wunused-function -DG_DISABLE_DEPRECATED -D_XOPEN_SOURCE=500 -DARCH=\"x86_64\" -DCOMMIT=\"v0.9.1-42-g6c64a7fe\" -DLIBDIR=\"/usr/local/lib/uzbl\" -DHAVE_LIBSOUP_CHECK_VERSION  -c -o src/uzbl-core.o src/uzbl-core.c
In file included from src/uzbl-core.h:4:0,
                 from src/uzbl-core.c:30:
src/webkit.h:4:10: fatal error: webkit/webkit.h: No such file or directory
 #include <webkit/webkit.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: src/uzbl-core.o] Error 1
```

**Comment by keis** [comment]
Is there a webkitgtk-dev(el) package you can install?

**Comment by nemanjan00** [comment]
![](https://i.imgur.com/oJsBk9g.png)

**Comment by keis** [comment]
oh wait, webkitgtk-3.0 that's not right. If you want to be running webkit2 like before you need to check out the `next` branch.

**Comment by nemanjan00** [comment]
There is no before for me. This is the first time I am installing that it is not from arch repo... 

I have no idea what I need... 

As you can see, I have none of those installed... 

There is the other one that is installled... 

![](https://i.imgur.com/YmMdclT.png)

**Comment by nemanjan00** [comment]
Ok, I did switch to next branch and make did work, but, fl still does nothing...

**Comment by nemanjan00** [comment]
Sorry, my bad, since I deleted old uzbl, there are no examples any more...

**Comment by nemanjan00** [comment]
Ok, works now! 

Thanks! 

Would you say it is safe to run in production?

**Comment by nemanjan00** [comment]
Now, how do we fix it on Arch?

**Comment by mathstuf** [comment]
> Would you say it is safe to run in production?

Define "production" please. I use it daily, but that doesn't really fit with many definitions of "widely usable" ;) .

> Now, how do we fix it on Arch?

File an issue on the AUR package please; there's not much we can do if the AUR branch is shipping mismatched configs/binaries.

**Comment by nemanjan00** [comment]
I mean in terms of security... 

It is not AUR repo but community repo... 

Ok, I did build it manually from next branch, but, scroll using hjkl does not work...

**Comment by nemanjan00** [comment]
According to documentation, if XDG_DATA_HOME is not defined, default one should be used. 

https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by nemanjan00** [comment]
Also, UZBL_UTIL_DIR does not seem to be defined. 

Should I define it or is it a bug?

**Comment by nemanjan00** [comment]
Reinstalling without PREFIX param fixed scroll and UTILS path problems. 

Ok, now I am left with just one problem: 

```
awk: cmd. line:4: fatal: cannot open file `/home/nemanjan00/.local/share/uzbl/cookies.txt' for reading (No such file or directory)
awk: cmd. line:4: fatal: cannot open file `/home/nemanjan00/.local/share/uzbl/session-cookies.txt' for reading (No such file or directory)
```
