### ISSUE TITLE
blank page, couldn't set ssl credentials, PROP_TIMELINE_PROFILING_ENABLED... ???

### ISSUE THREAD

**Issue by evanescente-ondine** [uzbl/uzbl#398]
uzbl-browser, freshly compiled from the next branch.

(uzbl-core:7129): libsoup-WARNING **: Could not set SSL credentials from '= /etc/ssl/certs/ca-certificates.crt': L'ouverture du fichier « /home/mehdi/uzbl/= /etc/ssl/certs/ca-certificates.crt » a échoué : Aucun fichier ou dossier de ce type
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-1~deb9u1-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
** Message: PROP_TIMELINE_PROFILING_ENABLED has been deprecated

with a blank white page window without status bar.

**Comment by keis** [comment]
it looks like you got an `=` in your path to your ssl-bundle. Are you using uzbl with an old config? The `set` command is now simply "set key value" and not "set key = value"

**Comment by evanescente-ondine** [comment]
Just compiled the last next commit from the next branch, nothing else.

**Comment by musteresel** [comment]
You should check your config eitherway.  If uzbl finds a config, then it doesn't copy / use its default one (the one from the examples).  So, if you are normally running a different (older) version of uzbl, it's likely that your config contains `=` in the set command, explaining your issue.
