### ISSUE TITLE
alerta.io is not displayed correctly

### ISSUE THREAD

**Issue by rsmartins78** [uzbl/uzbl#406]
Currently I use Nagios for alarm management, and I did the Alerta integration with the Nagios. 
But when I inserted the link in my raspberry used for monitoring, with the Screenly-OSE system, the view was broken. I tested the official try.alerta.io website, and the view was also broken.

![image](https://user-images.githubusercontent.com/33657518/43962620-9749d3fe-9c8e-11e8-9a5e-c9bace3de26c.png)

I tested the same website with surf browser and midori browser, and in both, the site is displayed correctly.

Steps to reproduce:
```
$ uzbl-browser -u http://try.alerta.io
```
In bash

**Comment by rsmartins78** [comment]
Error in log:
```
** Message: console message: http://try.alerta.io/js/controllers.js @76: SyntaxError: Unexpected use of reserved word 'let' in strict mode

** Message: console message: http://try.alerta.io/vendor/js/jquery.min.js @2: Error: [$injector:modulerr] http://errors.angularjs.org/1.5.11/$injector/modulerr?p0=alertaApp&p1=%5B%24injector%3Amodulerr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fmodulerr%3Fp0%3DalertaControllers%26p1%3D%255B%2524injector%253Anomod%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.5.11%252F%2524injector%252Fnomod%253Fp0%253DalertaControllers%250Ahttp%253A%252F%252Ftry.alerta.io%252Fvendor%252Fjs%252Fangular.min.js%253A6%253A431%250Ahttp%253A%252F%252Ftry.alerta.io%252Fvendor%252Fjs%252Fangular.min.js%253A25%253A236%250Ab%2540http%253A%252F%252Ftry.alerta.io%252Fvendor%252Fjs%252Fangular.min.js%253A24%253A283%250Ahttp%253A%252F%252Ftry.alerta.io%252Fvendor%252Fjs%252Fangular.min.js%253A25%253A21%250Ahttp%253A%252F%252Ftry.alerta.io%252Fvendor%252Fjs%252Fangular.min.js%253A40%253A19%250Aq%2540http%253A%252F%252Ftry.alerta.io%252Fvendor%252Fjs%252Fangular.min.js%253A7%253A375%250Ag%2540http%253A%252F%252Ftry.alerta.io%252Fvendor%252Fjs%252Fangular.min.js%253A39%253A383%250Ahttp%253A%252F%252Ftry.alerta.io%252Fvendor%252Fjs%252Fangular.min.js%253A40%253A35%250Aq%2540http%253A%252F%252Ftry.alerta.io%252Fvendor%252Fjs%252Fangular.min.js%253A7%253A375%250Ag%2540http%253A%252F%252Ftry.alerta.io%252Fvendor%252Fjs%252Fangular.min.js%253A39%253A383%250Afb%2540http%253A%252F%252Ftry.alerta.io%252Fvendor%252Fjs%252Fangular.min.js%253A43%253A382%250Ac%2540http%253A%252F%252Ftry.alerta.io%252Fvendor%252Fjs%252Fangular.min.js%253A21%253A21%250AGc%2540http%253A%252F%252Ftry.alerta.io%252Fvendor%252Fjs%252Fangular.min.js%253A21%253A333%250Ase%2540http%253A%252F%252Ftry.alerta.io%252Fvendor%252Fjs%252Fangular.min.js%253A20%253A2%250Ahttp%253A%252F%252Ftry.alerta.io%252Fvendor%252Fjs%252Fangular.min.js%253A323%253A56%250Aj%2540http%253A%252F%252Ftry.alerta.io%252Fvendor%252Fjs%252Fjquery.min.js%253A2%253A59428%250Ahttp%253A%252F%252Ftry.alerta.io%252Fvendor%252Fjs%252Fjquery.min.js%253A2%253A89673%0Ahttp%3A%2F%2Ftry.alerta.io%2Fvendor%2Fjs%2Fangular.min.js%3A6%3A431%0Ahttp%3A%2F%2Ftry.alerta.io%2Fvendor%2Fjs%2Fangular.min.js%3A40%3A294%0Aq%40http%3A%2F%2Ftry.alerta.io%2Fvendor%2Fjs%2Fangular.min.js%3A7%3A375%0Ag%40http%3A%2F%2Ftry.alerta.io%2Fvendor%2Fjs%2Fangular.min.js%3A39%3A383%0Ahttp%3A%2F%2Ftry.alerta.io%2Fvendor%2Fjs%2Fangular.min.js%3A40%3A35%0Aq%40http%3A%2F%2Ftry.alerta.io%2Fvendor%2Fjs%2Fangular.min.js%3A7%3A375%0Ag%40http%3A%2F%2Ftry.alerta.io%2Fvendor%2Fjs%2Fangular.min.js%3A39%3A383%0Afb%40http%3A%2F%2Ftry.alerta.io%2Fvendor%2Fjs%2Fangular.min.js%3A43%3A382%0Ac%40http%3A%2F%2Ftry.alerta.io%2Fvendor%2Fjs%2Fangular.min.js%3A21%3A21%0AGc%40http%3A%2F%2Ftry.alerta.io%2Fvendor%2Fjs%2Fangular.min.js%3A21%3A333%0Ase%40http%3A%2F%2Ftry.alerta.io%2Fvendor%2Fjs%2Fangular.min.js%3A20%3A2%0Ahttp%3A%2F%2Ftry.alerta.io%2Fvendor%2Fjs%2Fangular.min.js%3A323%3A56%0Aj%40http%3A%2F%2Ftry.alerta.io%2Fvendor%2Fjs%2Fjquery.min.js%3A2%3A59428%0Ahttp%3A%2F%2Ftry.alerta.io%2Fvendor%2Fjs%2Fjquery.min.js%3A2%3A89673
```

**Comment by jameskirsop** [comment]
@rsmartins78 are you using the pre-compiled version of uzbl that came with your distro, or trying to compile it yourself from either master or next?

**Comment by rsmartins78** [comment]
Pre compiled version embeded in Screenly-OSE

**Comment by jameskirsop** [comment]
You'll probably find that the uzbl packages available via offical RaspberryPi repos are well out of date when it comes to versions of WebKit because there hasn't been an update to uzbl in some time.

I forked Screenly a few years back for my own use after I found that it was lacking some features (which I've never got around to completing properly...). My [install script](https://github.com/jameskirsop/pisign/blob/development/misc/install.sh) grabs the latest source of uzbl/next and compiles it against Webkit2 - so that you're able to get most of the latest HTML5/CSS3 functionality. Take a look at what additional packages I pull, and the commands I've used to grab the source and compile in the script.

Without compiling against recent development libraries, simple things like gradient backgrounds don't work, not to mention more advanced things! I've got my fork running Grafana graphs and maps without a hitch, so I expect you'll have similar success with alerta.io.

**Comment by rsmartins78** [comment]
thank you for your reply.

I'll try to install your fork on another sdcard that I have, or install only new uzbl and webkit2 based on your script.

I'll post the result here soon.

**Comment by rsmartins78** [comment]
I've based myself in your script, but only on the part of latest UZBL install. I've changed the viewer.py code to work with newer uzbl version and it worked Ok.

I've tested too your entire script, but it doesn't worked for me, because the services doesn't started. But, I have my custom screenly image and your reply helped me a lot, so thank you.
