### ISSUE TITLE
Web feed not working at uzbl.org

### ISSUE THREAD

**Issue by sjehuda** [uzbl/uzbl#415]
Apparently, a concern of PHP https://www.uzbl.org/atom.xml

**Comment by mathstuf** [comment]
@barrucadu

**Comment by sjehuda** [comment]
It appears to be working!

**Comment by barrucadu** [comment]
Yep, fixed now.

**Comment by sjehuda** [comment]
~~Please add updated contents.~~

I'm adding this feed to the list of recommended feeds.
See https://openuserjs.org/scripts/sjehuda/Newspaper

Also, notice another issue: "Invalid Date".

**Comment by barrucadu** [comment]
I've fixed the dates of the latest two news entries.  Though, given that there's been no news since 2016 I don't think there's much use in sharing the feed more widely...

**Comment by sjehuda** [comment]
On Mon, 01 May 2023 13:12:45 -0700
Michael Walker ***@***.***> wrote:

> I've fixed the dates of the latest two news entries.  Though, given
> that there's been no news since 2016 I don't think there's much use
> in sharing the feed more widely...
> 

I won't advocate posting related "news and tips" on a Uzbl updates
feed, as that wouldn't be appropriate, unless it is an exceptional case.

I will add uzbl.org feed in next update.

Thank you

**Comment by keis** [comment]
Maybe it's time for a final news update saying "thanks for all the fish"

Though I must admit it was pretty nostalgic seeing uzbl in my github notifications :cat:

**Comment by sjehuda** [comment]
@keis how would such action make any good?
